# Generated by Django 5.1.4 on 2024-12-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_number", models.CharField(max_length=10, unique=True)),
                ("row_number", models.IntegerField()),
                ("status", models.BooleanField(default=False)),
            ],
        ),
    ]
